version: '2'

services:
  server:
    build: ./
    ports:
      - "8090:8090"
    container_name: goserver
    restart: always
    volumes:
      - ./:/app
    environment:
      PSQL_PORT:
      PSQL_HOST:
      PSQL_DBNAME:
      PSQL_USER:
      PSQL_PASSWORD:
      PORT:
